# Permalinks
permalink: pretty

# Setup
title: "Swadhin Routray(he/him)"
url: https://swadhinroutray.github.io
tagline: Privacy Engineering - CMU Co'24 | Ex-Oracle | CS - MIT, Manipal Co'22
paginate: 1000
paginate_path: "/blog/page:num/"
baseurl: ""

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Swadhin Routray
  url: https://twitter.com/routrayswadhin
  email: firstname.lastname@gmail.com

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/swadhinroutray

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
